### ISSUE TITLE
你这并行跑的更慢了。

### ISSUE THREAD

**Issue by gtwell** [weidafeng/CCPD2COCO#1]

**Comment by weidafeng** [comment]
你好，我补了multiprocessing的相关知识，之前的代码有点问题，实际上没有使用多线程。

可以试试现在速度有没有提升（理论上多线程同时处理多个文件，应该能加速），。

有一点需要注意，线程数不要超过cpu的线程数（笔记本一般6线程，服务器32）
```python
import multiprocessing
multiprocessing.cpu_count()
6
```

**Comment by gtwell** [comment]
感谢您的回复，我之前取消了多进程，后来也就没改了，有时间可以再试试。
